pipeline {
    agent any

    parameters {

    }

    options {

    }

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building webapp to container'
                acrQuickTask
                    gitPath: '', 
                    gitRefspec: '', 
                    gitRepo: '', 
                    imageNames: [[image: 'amdemoacr.azurecr.io/image:latest']], 
                    registryName: 'amdemoacr', 
                    resourceGroupName: 'amdemo', 
                    tarball: '', 
                    variant: ''
            }
            post {
                sh 'echo "Build successful'
            }
        }
        stage('Test') {
            steps {
                
            }
        }
        stage('Deploy') {
            steps {
                
            }
        }
    }
}